### ISSUE TITLE
ReadStats Problem

### ISSUE THREAD

**Issue by cpanel10x** [Jille00/RiseOfKingdomsNN#2]
![image](https://user-images.githubusercontent.com/5106227/85916159-2552ef80-b878-11ea-9a02-9fd87459795f.png)
I got this bug. Use your demo data has same problem

**Comment by cpanel10x** [comment]
Another question. How to detect non-alphabet name (Korea, Rus...etc). Thank you

**Comment by Jille00** [comment]
You'd have to retrain the neural network with added examples of those
